// Copyright (c) 2026 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool and should not edited
// by hand. See the translator.README.txt file in the tools directory for
// more information.
//
// $hash=972ee1a0748d1fabfcd917da0296fe3e7a3cefec$
//

#ifndef CEF_INCLUDE_CAPI_CEF_COMPOUND_OPERATION_CAPI_VERSIONS_H_
#define CEF_INCLUDE_CAPI_CEF_COMPOUND_OPERATION_CAPI_VERSIONS_H_
#pragma once

#if !defined(BUILDING_CEF_SHARED)
#error This file can be included DLL-side only
#endif

#include "include/capi/cef_base_capi.h"
#include "include/capi/cef_browser_capi_versions.h"
#include "include/capi/cef_values_capi_versions.h"
#include "include/internal/cef_types_wrappers.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct _cef_compound_operation_callback_0_t {
  cef_base_ref_counted_t base;
  void (CEF_CALLBACK *on_complete)(struct _cef_compound_operation_callback_0_t* self, int success, const cef_string_t* snapshot, const cef_string_t* screenshot_path, const cef_string_t* error);
} cef_compound_operation_callback_0_t;

typedef struct _cef_batch_query_callback_0_t {
  cef_base_ref_counted_t base;
  void (CEF_CALLBACK *on_complete)(struct _cef_batch_query_callback_0_t* self, int success, struct _cef_list_value_0_t* results, const cef_string_t* error);
} cef_batch_query_callback_0_t;

#ifdef __cplusplus
}
#endif

#endif  // CEF_INCLUDE_CAPI_CEF_COMPOUND_OPERATION_CAPI_VERSIONS_H_
