// Copyright (c) 2026 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool and should not edited
// by hand. See the translator.README.txt file in the tools directory for
// more information.
//
// $hash=ea10926ecefb9eb350c49ead2a97f16f4c02eb24$
//

#ifndef CEF_INCLUDE_CAPI_CEF_AUTOMATION_PROGRAM_CAPI_VERSIONS_H_
#define CEF_INCLUDE_CAPI_CEF_AUTOMATION_PROGRAM_CAPI_VERSIONS_H_
#pragma once

#if !defined(BUILDING_CEF_SHARED)
#error This file can be included DLL-side only
#endif

#include "include/capi/cef_base_capi.h"
#include "include/capi/cef_values_capi_versions.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct _cef_automation_program_0_t {
  cef_base_ref_counted_t base;
  int (CEF_CALLBACK *add_instruction)(struct _cef_automation_program_0_t* self, cef_automation_instruction_type_t type, struct _cef_dictionary_value_0_t* params);
  int (CEF_CALLBACK *get_instruction_count)(struct _cef_automation_program_0_t* self);
  void (CEF_CALLBACK *clear)(struct _cef_automation_program_0_t* self);
} cef_automation_program_0_t;

CEF_EXPORT cef_automation_program_0_t* cef_automation_program_create(void);

typedef struct _cef_automation_program_callback_0_t {
  cef_base_ref_counted_t base;
  void (CEF_CALLBACK *on_complete)(struct _cef_automation_program_callback_0_t* self, int success, struct _cef_list_value_0_t* results, int failed_index, const cef_string_t* error);
} cef_automation_program_callback_0_t;

#ifdef __cplusplus
}
#endif

#endif  // CEF_INCLUDE_CAPI_CEF_AUTOMATION_PROGRAM_CAPI_VERSIONS_H_
