// Copyright (c) 2026 Marshall A. Greenblatt. All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are
// met:
//
//    * Redistributions of source code must retain the above copyright
// notice, this list of conditions and the following disclaimer.
//    * Redistributions in binary form must reproduce the above
// copyright notice, this list of conditions and the following disclaimer
// in the documentation and/or other materials provided with the
// distribution.
//    * Neither the name of Google Inc. nor the name Chromium Embedded
// Framework nor the names of its contributors may be used to endorse
// or promote products derived from this software without specific prior
// written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
// "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
// LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
// A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
// OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
// SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
// LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool and should not edited
// by hand. See the translator.README.txt file in the tools directory for
// more information.
//
// $hash=f461793160df3243b3af015c51307cdc041ec974$
//

#ifndef CEF_INCLUDE_CAPI_CEF_COMPOUND_OPERATION_CAPI_H_
#define CEF_INCLUDE_CAPI_CEF_COMPOUND_OPERATION_CAPI_H_
#pragma once

#if defined(BUILDING_CEF_SHARED)
#error This file cannot be included DLL-side
#endif

#include "include/capi/cef_base_capi.h"
#include "include/capi/cef_browser_capi.h"
#include "include/capi/cef_values_capi.h"
#include "include/internal/cef_types_wrappers.h"

#ifdef __cplusplus
extern "C" {
#endif


///
/// Callback structure for compound operation results.
///
/// NOTE: This struct is allocated client-side.
///
typedef struct _cef_compound_operation_callback_t {
  ///
  /// Base structure.
  ///
  cef_base_ref_counted_t base;

  ///
  /// Called when the compound operation completes. |success| is true (1) if all
  /// steps completed successfully. |snapshot| contains the text snapshot if
  /// capture_snapshot was true (1). |screenshot_path| contains the screenshot
  /// path if capture_screenshot was true (1). |error| contains an error message
  /// if success is false (0).
  ///
  void (CEF_CALLBACK *on_complete)(struct _cef_compound_operation_callback_t* self, int success, const cef_string_t* snapshot, const cef_string_t* screenshot_path, const cef_string_t* error);
} cef_compound_operation_callback_t;


///
/// Callback structure for batch query results.
///
/// NOTE: This struct is allocated client-side.
///
typedef struct _cef_batch_query_callback_t {
  ///
  /// Base structure.
  ///
  cef_base_ref_counted_t base;

  ///
  /// Called when the batch query completes. |success| is true (1) if the query
  /// executed successfully. |results| contains a list of results, one per
  /// selector in the same order. Each result is a string (or list of strings if
  /// select_all was true (1)). |error| contains an error message if success is
  /// false (0).
  ///
  void (CEF_CALLBACK *on_complete)(struct _cef_batch_query_callback_t* self, int success, struct _cef_list_value_t* results, const cef_string_t* error);
} cef_batch_query_callback_t;


#ifdef __cplusplus
}
#endif

#endif  // CEF_INCLUDE_CAPI_CEF_COMPOUND_OPERATION_CAPI_H_
