// Copyright (c) 2026 Marshall A. Greenblatt. All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are
// met:
//
//    * Redistributions of source code must retain the above copyright
// notice, this list of conditions and the following disclaimer.
//    * Redistributions in binary form must reproduce the above
// copyright notice, this list of conditions and the following disclaimer
// in the documentation and/or other materials provided with the
// distribution.
//    * Neither the name of Google Inc. nor the name Chromium Embedded
// Framework nor the names of its contributors may be used to endorse
// or promote products derived from this software without specific prior
// written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
// "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
// LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
// A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
// OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
// SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
// LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool and should not edited
// by hand. See the translator.README.txt file in the tools directory for
// more information.
//
// $hash=f570dea82a1a8a4cd033c17a8cb942761c69fced$
//

#ifndef CEF_INCLUDE_CAPI_CEF_AUTOMATION_PROGRAM_CAPI_H_
#define CEF_INCLUDE_CAPI_CEF_AUTOMATION_PROGRAM_CAPI_H_
#pragma once

#if defined(BUILDING_CEF_SHARED)
#error This file cannot be included DLL-side
#endif

#include "include/capi/cef_base_capi.h"
#include "include/capi/cef_values_capi.h"

#ifdef __cplusplus
extern "C" {
#endif


///
/// Represents a sequence of automation instructions that can be executed as a
/// single batch, reducing IPC round-trips. Each instruction in the program is
/// dispatched through the normal Blink event pipeline with configurable delays
/// between steps.
///
/// NOTE: This is an additive API. Existing CDP commands remain unchanged.
/// Agents must be retrained to use this structure.
///
/// NOTE: This struct is allocated DLL-side.
///
typedef struct _cef_automation_program_t {
  ///
  /// Base structure.
  ///
  cef_base_ref_counted_t base;

  ///
  /// Add an instruction to the program. |type| is the instruction type.
  /// |params| contains instruction-specific parameters as a dictionary. Returns
  /// the instruction index.
  ///
  int (CEF_CALLBACK *add_instruction)(struct _cef_automation_program_t* self, cef_automation_instruction_type_t type, struct _cef_dictionary_value_t* params);

  ///
  /// Get the number of instructions in the program.
  ///
  int (CEF_CALLBACK *get_instruction_count)(struct _cef_automation_program_t* self);

  ///
  /// Clear all instructions.
  ///
  void (CEF_CALLBACK *clear)(struct _cef_automation_program_t* self);
} cef_automation_program_t;


///
/// Instruction types that can be added to the program. The enum values are
/// defined in cef_automation_instruction_type_t.
///
/// Create a new NULL automation program.
///
CEF_EXPORT cef_automation_program_t* cef_automation_program_create(void);


///
/// Callback structure for automation program execution results.
///
/// NOTE: This struct is allocated client-side.
///
typedef struct _cef_automation_program_callback_t {
  ///
  /// Base structure.
  ///
  cef_base_ref_counted_t base;

  ///
  /// Called when the program completes execution. |success| is true (1) if all
  /// instructions completed successfully. |results| contains a list of results,
  /// one per instruction. |failed_index| is the index of the first failed
  /// instruction, or -1. |error| contains an error message if success is false
  /// (0).
  ///
  void (CEF_CALLBACK *on_complete)(struct _cef_automation_program_callback_t* self, int success, struct _cef_list_value_t* results, int failed_index, const cef_string_t* error);
} cef_automation_program_callback_t;


#ifdef __cplusplus
}
#endif

#endif  // CEF_INCLUDE_CAPI_CEF_AUTOMATION_PROGRAM_CAPI_H_
