// Copyright (c) 2026 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=40a077601fc6065cf80c6541cfa0d88362f5551b$
//

#ifndef CEF_LIBCEF_DLL_CTOCPP_AUTOMATION_PROGRAM_CTOCPP_H_
#define CEF_LIBCEF_DLL_CTOCPP_AUTOMATION_PROGRAM_CTOCPP_H_
#pragma once

#if !defined(WRAPPING_CEF_SHARED)
#error This file can be included wrapper-side only
#endif

#include "include/cef_automation_program.h"
#include "include/capi/cef_automation_program_capi.h"
#include "libcef_dll/ctocpp/ctocpp_ref_counted.h"

// Wrap a C structure with a C++ class.
// This class may be instantiated and accessed wrapper-side only.
class CefAutomationProgramCToCpp
    : public CefCToCppRefCounted<CefAutomationProgramCToCpp, CefAutomationProgram, cef_automation_program_t> {
 public:
  CefAutomationProgramCToCpp();
  virtual ~CefAutomationProgramCToCpp();

  // CefAutomationProgram methods.
  int AddInstruction(cef_automation_instruction_type_t type, CefRefPtr<CefDictionaryValue> params) override;
  int GetInstructionCount() override;
  void Clear() override;
};

constexpr auto CefAutomationProgramCToCpp_Wrap = CefAutomationProgramCToCpp::Wrap;
constexpr auto CefAutomationProgramCToCpp_Unwrap = CefAutomationProgramCToCpp::Unwrap;

#endif  // CEF_LIBCEF_DLL_CTOCPP_AUTOMATION_PROGRAM_CTOCPP_H_
