// Copyright (c) 2026 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=504fd708527231685696890dad21976651a2293f$
//

#include "include/cef_api_hash.h"
#include "libcef_dll/cpptoc/list_value_cpptoc.h"
#include "libcef_dll/ctocpp/automation_program_callback_ctocpp.h"
#include "libcef_dll/shutdown_checker.h"


// VIRTUAL METHODS FOR VERSION 0 - Body may be edited by hand.

NO_SANITIZE("cfi-icall") void CefAutomationProgramCallback_0_CToCpp::OnComplete(bool success, CefRefPtr<CefListValue> results, int failed_index, const CefString& error) {
  shutdown_checker::AssertNotShutdown();

  auto* _struct = GetStruct();
  if (!_struct->on_complete) {
    return;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Unverified params: results, error

  // Execute
  _struct->on_complete(_struct,
      success,
      CefListValueCppToC_Wrap(results),
      failed_index,
      error.GetStruct());
}

// CONSTRUCTOR FOR VERSION 0 - Do not edit by hand.

CefAutomationProgramCallback_0_CToCpp::CefAutomationProgramCallback_0_CToCpp() {
  const int version = cef_api_version();
  LOG_IF(FATAL, version < 0) << __func__ << " called with invalid version " << version;
}

// DESTRUCTOR FOR VERSION 0 - Do not edit by hand.

CefAutomationProgramCallback_0_CToCpp::~CefAutomationProgramCallback_0_CToCpp() {
  shutdown_checker::AssertNotShutdown();
}

template<> cef_automation_program_callback_0_t* CefCToCppRefCounted<CefAutomationProgramCallback_0_CToCpp, CefAutomationProgramCallback, cef_automation_program_callback_0_t>::UnwrapDerived(CefWrapperType type, CefAutomationProgramCallback* c) {
  NOTREACHED() << __func__ << " called with unexpected class type " << type;
}

template<> CefWrapperType CefCToCppRefCounted<CefAutomationProgramCallback_0_CToCpp, CefAutomationProgramCallback, cef_automation_program_callback_0_t>::kWrapperType = WT_AUTOMATION_PROGRAM_CALLBACK;


