// Copyright (c) 2026 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=b820d67e64088964198269fb3c2e61071ab88695$
//

#ifndef CEF_LIBCEF_DLL_CTOCPP_AUTOMATION_PROGRAM_CALLBACK_CTOCPP_H_
#define CEF_LIBCEF_DLL_CTOCPP_AUTOMATION_PROGRAM_CALLBACK_CTOCPP_H_
#pragma once

#if !defined(BUILDING_CEF_SHARED)
#error This file can be included DLL-side only
#endif

#include "include/cef_automation_program.h"
#include "include/capi/cef_automation_program_capi_versions.h"
#include "libcef_dll/ctocpp/ctocpp_ref_counted.h"

// Wrap a C structure with a C++ class at API version 0.
// This class may be instantiated and accessed DLL-side only.
class CefAutomationProgramCallback_0_CToCpp
    : public CefCToCppRefCounted<CefAutomationProgramCallback_0_CToCpp, CefAutomationProgramCallback, cef_automation_program_callback_0_t> {
 public:
  CefAutomationProgramCallback_0_CToCpp();
  virtual ~CefAutomationProgramCallback_0_CToCpp();

  // CefAutomationProgramCallback methods.
  void OnComplete(bool success, CefRefPtr<CefListValue> results, int failed_index, const CefString& error) override;
};

constexpr auto CefAutomationProgramCallbackCToCpp_Wrap = CefAutomationProgramCallback_0_CToCpp::Wrap;
constexpr auto CefAutomationProgramCallbackCToCpp_Unwrap = CefAutomationProgramCallback_0_CToCpp::Unwrap;

#endif  // CEF_LIBCEF_DLL_CTOCPP_AUTOMATION_PROGRAM_CALLBACK_CTOCPP_H_
