// Copyright (c) 2026 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=341edbb2b93157aa63dde761f5165f59f84d6c7f$
//

#include "libcef_dll/ctocpp/automation_program_ctocpp.h"
#include "libcef_dll/ctocpp/dictionary_value_ctocpp.h"
#include "libcef_dll/shutdown_checker.h"


// STATIC METHODS - Body may be edited by hand.

NO_SANITIZE("cfi-icall") CefRefPtr<CefAutomationProgram> CefAutomationProgram::Create() {
  shutdown_checker::AssertNotShutdown();

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  auto* _retval = cef_automation_program_create();

  // Return type: refptr_same
  return CefAutomationProgramCToCpp_Wrap(_retval);
}


// VIRTUAL METHODS - Body may be edited by hand.

NO_SANITIZE("cfi-icall") int CefAutomationProgramCToCpp::AddInstruction(cef_automation_instruction_type_t type, CefRefPtr<CefDictionaryValue> params) {
  shutdown_checker::AssertNotShutdown();

  auto* _struct = GetStruct();
  if (!_struct->add_instruction) {
    return 0;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Verify param: params; type: refptr_same
  DCHECK(params.get());
  if (!params.get()) {
    return 0;
  }

  // Execute
  int _retval = _struct->add_instruction(_struct,
      type,
      CefDictionaryValueCToCpp_Unwrap(params));

  // Return type: simple
  return _retval;
}

NO_SANITIZE("cfi-icall") int CefAutomationProgramCToCpp::GetInstructionCount() {
  shutdown_checker::AssertNotShutdown();

  auto* _struct = GetStruct();
  if (!_struct->get_instruction_count) {
    return 0;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  int _retval = _struct->get_instruction_count(_struct);

  // Return type: simple
  return _retval;
}

NO_SANITIZE("cfi-icall") void CefAutomationProgramCToCpp::Clear() {
  shutdown_checker::AssertNotShutdown();

  auto* _struct = GetStruct();
  if (!_struct->clear) {
    return;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  _struct->clear(_struct);
}

// CONSTRUCTOR - Do not edit by hand.

CefAutomationProgramCToCpp::CefAutomationProgramCToCpp() {
}

// DESTRUCTOR - Do not edit by hand.

CefAutomationProgramCToCpp::~CefAutomationProgramCToCpp() {
  shutdown_checker::AssertNotShutdown();
}

template<> cef_automation_program_t* CefCToCppRefCounted<CefAutomationProgramCToCpp, CefAutomationProgram, cef_automation_program_t>::UnwrapDerived(CefWrapperType type, CefAutomationProgram* c) {
  CHECK(false) << __func__ << " called with unexpected class type " << type;
  return nullptr;
}

template<> CefWrapperType CefCToCppRefCounted<CefAutomationProgramCToCpp, CefAutomationProgram, cef_automation_program_t>::kWrapperType = WT_AUTOMATION_PROGRAM;


