// Copyright (c) 2026 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=7f6c05e76145fe3c519bde4d00bd125eb3320a29$
//

#include "include/cef_api_hash.h"
#include "libcef_dll/cpptoc/list_value_cpptoc.h"
#include "libcef_dll/ctocpp/batch_query_callback_ctocpp.h"
#include "libcef_dll/shutdown_checker.h"


// VIRTUAL METHODS FOR VERSION 0 - Body may be edited by hand.

NO_SANITIZE("cfi-icall") void CefBatchQueryCallback_0_CToCpp::OnComplete(bool success, CefRefPtr<CefListValue> results, const CefString& error) {
  shutdown_checker::AssertNotShutdown();

  auto* _struct = GetStruct();
  if (!_struct->on_complete) {
    return;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Unverified params: results, error

  // Execute
  _struct->on_complete(_struct,
      success,
      CefListValueCppToC_Wrap(results),
      error.GetStruct());
}

// CONSTRUCTOR FOR VERSION 0 - Do not edit by hand.

CefBatchQueryCallback_0_CToCpp::CefBatchQueryCallback_0_CToCpp() {
  const int version = cef_api_version();
  LOG_IF(FATAL, version < 0) << __func__ << " called with invalid version " << version;
}

// DESTRUCTOR FOR VERSION 0 - Do not edit by hand.

CefBatchQueryCallback_0_CToCpp::~CefBatchQueryCallback_0_CToCpp() {
  shutdown_checker::AssertNotShutdown();
}

template<> cef_batch_query_callback_0_t* CefCToCppRefCounted<CefBatchQueryCallback_0_CToCpp, CefBatchQueryCallback, cef_batch_query_callback_0_t>::UnwrapDerived(CefWrapperType type, CefBatchQueryCallback* c) {
  NOTREACHED() << __func__ << " called with unexpected class type " << type;
}

template<> CefWrapperType CefCToCppRefCounted<CefBatchQueryCallback_0_CToCpp, CefBatchQueryCallback, cef_batch_query_callback_0_t>::kWrapperType = WT_BATCH_QUERY_CALLBACK;


