// Copyright (c) 2026 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=d6d831d8aea1ca74b5ba38a3ead1051321e7536e$
//

#ifndef CEF_LIBCEF_DLL_CTOCPP_BATCH_QUERY_CALLBACK_CTOCPP_H_
#define CEF_LIBCEF_DLL_CTOCPP_BATCH_QUERY_CALLBACK_CTOCPP_H_
#pragma once

#if !defined(BUILDING_CEF_SHARED)
#error This file can be included DLL-side only
#endif

#include "include/cef_compound_operation.h"
#include "include/capi/cef_compound_operation_capi_versions.h"
#include "libcef_dll/ctocpp/ctocpp_ref_counted.h"

// Wrap a C structure with a C++ class at API version 0.
// This class may be instantiated and accessed DLL-side only.
class CefBatchQueryCallback_0_CToCpp
    : public CefCToCppRefCounted<CefBatchQueryCallback_0_CToCpp, CefBatchQueryCallback, cef_batch_query_callback_0_t> {
 public:
  CefBatchQueryCallback_0_CToCpp();
  virtual ~CefBatchQueryCallback_0_CToCpp();

  // CefBatchQueryCallback methods.
  void OnComplete(bool success, CefRefPtr<CefListValue> results, const CefString& error) override;
};

constexpr auto CefBatchQueryCallbackCToCpp_Wrap = CefBatchQueryCallback_0_CToCpp::Wrap;
constexpr auto CefBatchQueryCallbackCToCpp_Unwrap = CefBatchQueryCallback_0_CToCpp::Unwrap;

#endif  // CEF_LIBCEF_DLL_CTOCPP_BATCH_QUERY_CALLBACK_CTOCPP_H_
