// Copyright (c) 2026 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=df615f4c9bb81ba11c44a8f4bd7e4f9601f08ac1$
//

#include "libcef_dll/cpptoc/eval_snapshot_callback_cpptoc.h"
#include "libcef_dll/cpptoc/screenshot_callback_cpptoc.h"
#include "libcef_dll/cpptoc/string_visitor_cpptoc.h"
#include "libcef_dll/ctocpp/browser_capture_ctocpp.h"
#include "libcef_dll/shutdown_checker.h"


// VIRTUAL METHODS - Body may be edited by hand.

NO_SANITIZE("cfi-icall") void CefBrowserCaptureCToCpp::Snapshot(const CefSnapshotSettings& settings, CefRefPtr<CefStringVisitor> callback) {
  shutdown_checker::AssertNotShutdown();

  auto* _struct = GetStruct();
  if (!_struct->snapshot) {
    return;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Verify param: callback; type: refptr_diff
  DCHECK(callback.get());
  if (!callback.get()) {
    return;
  }

  // Execute
  _struct->snapshot(_struct,
      &settings,
      CefStringVisitorCppToC_Wrap(callback));
}

NO_SANITIZE("cfi-icall") void CefBrowserCaptureCToCpp::EvalThenSnapshot(const CefString& code, const CefSnapshotSettings& settings, CefRefPtr<CefEvalSnapshotCallback> callback){
  shutdown_checker::AssertNotShutdown();

  auto* _struct = GetStruct();
  if (!_struct->eval_then_snapshot) {
    return;
  }

  DCHECK(callback.get());
  if (!callback.get()) {
    return;
  }

  _struct->eval_then_snapshot(_struct, code.GetStruct(), &settings,
                              CefEvalSnapshotCallbackCppToC_Wrap(callback));
}

NO_SANITIZE("cfi-icall") void CefBrowserCaptureCToCpp::CaptureAnnotatedScreenshot(const CefString& path, const CefAnnotatedScreenshotSettings& settings, CefRefPtr<CefScreenshotCallback> callback) {
  shutdown_checker::AssertNotShutdown();

  auto* _struct = GetStruct();
  if (!_struct->capture_annotated_screenshot) {
    return;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Verify param: callback; type: refptr_diff
  DCHECK(callback.get());
  if (!callback.get()) {
    return;
  }
  // Unverified params: path

  // Execute
  _struct->capture_annotated_screenshot(_struct,
      path.GetStruct(),
      &settings,
      CefScreenshotCallbackCppToC_Wrap(callback));
}

// CONSTRUCTOR - Do not edit by hand.

CefBrowserCaptureCToCpp::CefBrowserCaptureCToCpp() {
}

// DESTRUCTOR - Do not edit by hand.

CefBrowserCaptureCToCpp::~CefBrowserCaptureCToCpp() {
  shutdown_checker::AssertNotShutdown();
}

template<> cef_browser_capture_t* CefCToCppRefCounted<CefBrowserCaptureCToCpp, CefBrowserCapture, cef_browser_capture_t>::UnwrapDerived(CefWrapperType type, CefBrowserCapture* c) {
  CHECK(false) << __func__ << " called with unexpected class type " << type;
  return nullptr;
}

template<> CefWrapperType CefCToCppRefCounted<CefBrowserCaptureCToCpp, CefBrowserCapture, cef_browser_capture_t>::kWrapperType = WT_BROWSER_CAPTURE;


