// Copyright (c) 2026 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=5a4b1c73fcab1d489872ad7dd35ca5a40006f5a5$
//

#ifndef CEF_LIBCEF_DLL_CTOCPP_COMPOUND_OPERATION_CALLBACK_CTOCPP_H_
#define CEF_LIBCEF_DLL_CTOCPP_COMPOUND_OPERATION_CALLBACK_CTOCPP_H_
#pragma once

#if !defined(BUILDING_CEF_SHARED)
#error This file can be included DLL-side only
#endif

#include "include/cef_compound_operation.h"
#include "include/capi/cef_compound_operation_capi_versions.h"
#include "libcef_dll/ctocpp/ctocpp_ref_counted.h"

// Wrap a C structure with a C++ class at API version 0.
// This class may be instantiated and accessed DLL-side only.
class CefCompoundOperationCallback_0_CToCpp
    : public CefCToCppRefCounted<CefCompoundOperationCallback_0_CToCpp, CefCompoundOperationCallback, cef_compound_operation_callback_0_t> {
 public:
  CefCompoundOperationCallback_0_CToCpp();
  virtual ~CefCompoundOperationCallback_0_CToCpp();

  // CefCompoundOperationCallback methods.
  void OnComplete(bool success, const CefString& snapshot, const CefString& screenshot_path, const CefString& error) override;
};

constexpr auto CefCompoundOperationCallbackCToCpp_Wrap = CefCompoundOperationCallback_0_CToCpp::Wrap;
constexpr auto CefCompoundOperationCallbackCToCpp_Unwrap = CefCompoundOperationCallback_0_CToCpp::Unwrap;

#endif  // CEF_LIBCEF_DLL_CTOCPP_COMPOUND_OPERATION_CALLBACK_CTOCPP_H_
