// Copyright (c) 2026 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=a48d715152c05606373412fd2da1b00182e59a30$
//

#include "include/cef_api_hash.h"
#include "libcef_dll/cpptoc/automation_program_cpptoc.h"
#include "libcef_dll/cpptoc/dictionary_value_cpptoc.h"
#include "libcef_dll/shutdown_checker.h"

// GLOBAL FUNCTIONS - Body may be edited by hand.

CEF_EXPORT cef_automation_program_0_t* cef_automation_program_create() {
  shutdown_checker::AssertNotShutdown();

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  CefRefPtr<CefAutomationProgram> _retval = CefAutomationProgram::Create();

  // Return type: refptr_same
  return CefAutomationProgramCppToC_Wrap(_retval);
}

namespace {

// MEMBER FUNCTIONS FOR VERSION 0 - Body may be edited by hand.

int CEF_CALLBACK automation_program_add_instruction(struct _cef_automation_program_0_t* self, cef_automation_instruction_type_t type, struct _cef_dictionary_value_0_t* params) {
  shutdown_checker::AssertNotShutdown();

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  DCHECK(self);
  if (!self) {
    return 0;
  }
  // Verify param: params; type: refptr_same
  DCHECK(params);
  if (!params) {
    return 0;
  }

  // Execute
  int _retval = CefAutomationProgram_0_CppToC::Get(self)->AddInstruction(
      type,
      CefDictionaryValueCppToC_Unwrap(params));

  // Return type: simple
  return _retval;
}

int CEF_CALLBACK automation_program_get_instruction_count(struct _cef_automation_program_0_t* self) {
  shutdown_checker::AssertNotShutdown();

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  DCHECK(self);
  if (!self) {
    return 0;
  }

  // Execute
  int _retval = CefAutomationProgram_0_CppToC::Get(self)->GetInstructionCount();

  // Return type: simple
  return _retval;
}

void CEF_CALLBACK automation_program_clear(struct _cef_automation_program_0_t* self) {
  shutdown_checker::AssertNotShutdown();

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  DCHECK(self);
  if (!self) {
    return;
  }

  // Execute
  CefAutomationProgram_0_CppToC::Get(self)->Clear();
}

}  // namespace

// CONSTRUCTOR FOR VERSION 0 - Do not edit by hand.

CefAutomationProgram_0_CppToC::CefAutomationProgram_0_CppToC() {
  const int version = cef_api_version();
  LOG_IF(FATAL, version < 0) << __func__ << " called with invalid version " << version;

  GetStruct()->add_instruction = automation_program_add_instruction;
  GetStruct()->get_instruction_count = automation_program_get_instruction_count;
  GetStruct()->clear = automation_program_clear;
}

// DESTRUCTOR FOR VERSION 0 - Do not edit by hand.

CefAutomationProgram_0_CppToC::~CefAutomationProgram_0_CppToC() {
  shutdown_checker::AssertNotShutdown();
}

template<> CefRefPtr<CefAutomationProgram> CefCppToCRefCounted<CefAutomationProgram_0_CppToC, CefAutomationProgram, cef_automation_program_0_t>::UnwrapDerived(CefWrapperType type, cef_automation_program_0_t* s) {
  NOTREACHED() << __func__ << " called with unexpected class type " << type;
}

template<> CefWrapperType CefCppToCRefCounted<CefAutomationProgram_0_CppToC, CefAutomationProgram, cef_automation_program_0_t>::kWrapperType = WT_AUTOMATION_PROGRAM;


