// Copyright (c) 2026 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=34c4aa882e7eb8e2c3df9e88b7def1c64a6e0c67$
//

#ifndef CEF_LIBCEF_DLL_CPPTOC_AUTOMATION_PROGRAM_CALLBACK_CPPTOC_H_
#define CEF_LIBCEF_DLL_CPPTOC_AUTOMATION_PROGRAM_CALLBACK_CPPTOC_H_
#pragma once

#if !defined(WRAPPING_CEF_SHARED)
#error This file can be included wrapper-side only
#endif

#include "include/cef_automation_program.h"
#include "include/capi/cef_automation_program_capi.h"
#include "libcef_dll/cpptoc/cpptoc_ref_counted.h"

// Wrap a C++ class with a C structure.
// This class may be instantiated and accessed wrapper-side only.
class CefAutomationProgramCallbackCppToC
    : public CefCppToCRefCounted<CefAutomationProgramCallbackCppToC, CefAutomationProgramCallback, cef_automation_program_callback_t> {
 public:
  CefAutomationProgramCallbackCppToC();
  virtual ~CefAutomationProgramCallbackCppToC();
};

constexpr auto CefAutomationProgramCallbackCppToC_Wrap = CefAutomationProgramCallbackCppToC::Wrap;
constexpr auto CefAutomationProgramCallbackCppToC_Unwrap = CefAutomationProgramCallbackCppToC::Unwrap;

#endif  // CEF_LIBCEF_DLL_CPPTOC_AUTOMATION_PROGRAM_CALLBACK_CPPTOC_H_
