// Copyright (c) 2026 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=d20a3146f0662cb944ca7d7f103150345b31df15$
//

#ifndef CEF_LIBCEF_DLL_CPPTOC_AUTOMATION_PROGRAM_CPPTOC_H_
#define CEF_LIBCEF_DLL_CPPTOC_AUTOMATION_PROGRAM_CPPTOC_H_
#pragma once

#if !defined(BUILDING_CEF_SHARED)
#error This file can be included DLL-side only
#endif

#include "include/cef_automation_program.h"
#include "include/capi/cef_automation_program_capi_versions.h"
#include "libcef_dll/cpptoc/cpptoc_ref_counted.h"

// Wrap a C++ class with a C structure at API version 0.
// This class may be instantiated and accessed DLL-side only.
class CefAutomationProgram_0_CppToC
    : public CefCppToCRefCounted<CefAutomationProgram_0_CppToC, CefAutomationProgram, cef_automation_program_0_t> {
 public:
  CefAutomationProgram_0_CppToC();
  virtual ~CefAutomationProgram_0_CppToC();
};

constexpr auto CefAutomationProgramCppToC_Wrap = CefAutomationProgram_0_CppToC::Wrap;
constexpr auto CefAutomationProgramCppToC_Unwrap = CefAutomationProgram_0_CppToC::Unwrap;

#endif  // CEF_LIBCEF_DLL_CPPTOC_AUTOMATION_PROGRAM_CPPTOC_H_
