// Copyright (c) 2026 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=c60468dbbfcaed27641dab7d13c4c4e759401983$
//

#include "libcef_dll/cpptoc/automation_program_callback_cpptoc.h"
#include "libcef_dll/ctocpp/list_value_ctocpp.h"
#include "libcef_dll/shutdown_checker.h"

namespace {

// MEMBER FUNCTIONS - Body may be edited by hand.

void CEF_CALLBACK automation_program_callback_on_complete(struct _cef_automation_program_callback_t* self, int success, struct _cef_list_value_t* results, int failed_index, const cef_string_t* error) {
  shutdown_checker::AssertNotShutdown();

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  DCHECK(self);
  if (!self) {
    return;
  }
  // Unverified params: results, error

  // Execute
  CefAutomationProgramCallbackCppToC::Get(self)->OnComplete(
      success?true:false,
      CefListValueCToCpp_Wrap(results),
      failed_index,
      CefString(error));
}

}  // namespace

// CONSTRUCTOR - Do not edit by hand.

CefAutomationProgramCallbackCppToC::CefAutomationProgramCallbackCppToC() {
  GetStruct()->on_complete = automation_program_callback_on_complete;
}

// DESTRUCTOR - Do not edit by hand.

CefAutomationProgramCallbackCppToC::~CefAutomationProgramCallbackCppToC() {
  shutdown_checker::AssertNotShutdown();
}

template<> CefRefPtr<CefAutomationProgramCallback> CefCppToCRefCounted<CefAutomationProgramCallbackCppToC, CefAutomationProgramCallback, cef_automation_program_callback_t>::UnwrapDerived(CefWrapperType type, cef_automation_program_callback_t* s) {
  CHECK(false) << __func__ << " called with unexpected class type " << type;
  return nullptr;
}

template<> CefWrapperType CefCppToCRefCounted<CefAutomationProgramCallbackCppToC, CefAutomationProgramCallback, cef_automation_program_callback_t>::kWrapperType = WT_AUTOMATION_PROGRAM_CALLBACK;


