// Copyright (c) 2026 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=cf16ecf9dce449fd76307ba3dfb7ea9e02d77bb1$
//

#ifndef CEF_LIBCEF_DLL_CPPTOC_BATCH_QUERY_CALLBACK_CPPTOC_H_
#define CEF_LIBCEF_DLL_CPPTOC_BATCH_QUERY_CALLBACK_CPPTOC_H_
#pragma once

#if !defined(WRAPPING_CEF_SHARED)
#error This file can be included wrapper-side only
#endif

#include "include/cef_compound_operation.h"
#include "include/capi/cef_compound_operation_capi.h"
#include "libcef_dll/cpptoc/cpptoc_ref_counted.h"

// Wrap a C++ class with a C structure.
// This class may be instantiated and accessed wrapper-side only.
class CefBatchQueryCallbackCppToC
    : public CefCppToCRefCounted<CefBatchQueryCallbackCppToC, CefBatchQueryCallback, cef_batch_query_callback_t> {
 public:
  CefBatchQueryCallbackCppToC();
  virtual ~CefBatchQueryCallbackCppToC();
};

constexpr auto CefBatchQueryCallbackCppToC_Wrap = CefBatchQueryCallbackCppToC::Wrap;
constexpr auto CefBatchQueryCallbackCppToC_Unwrap = CefBatchQueryCallbackCppToC::Unwrap;

#endif  // CEF_LIBCEF_DLL_CPPTOC_BATCH_QUERY_CALLBACK_CPPTOC_H_
