// Copyright (c) 2026 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=1bc48fb3033db5d600d86a2eac415a76748dc44c$
//

#include "libcef_dll/cpptoc/compound_operation_callback_cpptoc.h"
#include "libcef_dll/shutdown_checker.h"

namespace {

// MEMBER FUNCTIONS - Body may be edited by hand.

void CEF_CALLBACK compound_operation_callback_on_complete(struct _cef_compound_operation_callback_t* self, int success, const cef_string_t* snapshot, const cef_string_t* screenshot_path, const cef_string_t* error) {
  shutdown_checker::AssertNotShutdown();

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  DCHECK(self);
  if (!self) {
    return;
  }
  // Unverified params: snapshot, screenshot_path, error

  // Execute
  CefCompoundOperationCallbackCppToC::Get(self)->OnComplete(
      success?true:false,
      CefString(snapshot),
      CefString(screenshot_path),
      CefString(error));
}

}  // namespace

// CONSTRUCTOR - Do not edit by hand.

CefCompoundOperationCallbackCppToC::CefCompoundOperationCallbackCppToC() {
  GetStruct()->on_complete = compound_operation_callback_on_complete;
}

// DESTRUCTOR - Do not edit by hand.

CefCompoundOperationCallbackCppToC::~CefCompoundOperationCallbackCppToC() {
  shutdown_checker::AssertNotShutdown();
}

template<> CefRefPtr<CefCompoundOperationCallback> CefCppToCRefCounted<CefCompoundOperationCallbackCppToC, CefCompoundOperationCallback, cef_compound_operation_callback_t>::UnwrapDerived(CefWrapperType type, cef_compound_operation_callback_t* s) {
  CHECK(false) << __func__ << " called with unexpected class type " << type;
  return nullptr;
}

template<> CefWrapperType CefCppToCRefCounted<CefCompoundOperationCallbackCppToC, CefCompoundOperationCallback, cef_compound_operation_callback_t>::kWrapperType = WT_COMPOUND_OPERATION_CALLBACK;


